### ISSUE TITLE
bug: `foundry.toml` behaves unexpectedly

### ISSUE THREAD

**Issue by Autoparallel** [Will-Smith11/sks#4]
# Problem

- [ ] When I use `sks install` with my `sks.toml` set like so:
```toml
name = "contracts/"

[deps]
uniswap_v2_core = "https://github.com/Uniswap/v2-core.git"
```

I get a lot of extra additions to my `foundry.toml`. Are each one of these intended? I was expecting to have the remappings populated, but there is a bunch more. 

- [ ] #5

--- 

## Questions
- Which parts above are intended?
- Should the `name` field of the `sks.toml` be named `directory` or something instead? It wasn't clear to me this was for that until I ran `sks install`!
